### ISSUE TITLE
Demo not working. One more thing.

### ISSUE THREAD

**Issue by arjunmenon** [henriquea/minigrid#10]
Hey
Your link to the demo seems to not work. I checked the console, it says ```ReferenceError: minigrid is not defined```

Also, is there a horizontal version to it?

Thanks.

**Comment by henriquea** [comment]
Hey @arjunmenon thanks! I did a refactor in the page and forgot to update the links.

What do you mean with horizontal? This one? http://output.jsbin.com/maroda/9/

**Comment by arjunmenon** [comment]
By horizontal version, I imply a kind of horizontal scrolling website with your grid system. Is it possible.
Like what the new Myspace has?
It would be real cool!

**Comment by henriquea** [comment]
@arjunmenon yes it should work fine as long you call minigrid again to update it.
