### ISSUE TITLE
Optionally use Node as containerSelector

### ISSUE THREAD

**Issue by jodyheavener** [henriquea/minigrid#14]
I am using multiple instances of minigrid on elements with the same class, so I needed a way to scope the `itemsNodeList` QSA to children of a given container.

All I did was update L8 to:

```javascript
var containerEle = containerSelector instanceof Node ? containerSelector : document.querySelector(containerSelector);
```

I can submit a PR if you'd like, or if you don't want it that's cool too :smiley:

**Comment by henriquea** [comment]
@jodyheavener that's interesting. I like the idea to keep it as selector in the same way as `querySelector` works. 

Any reason why don't you want to use ids i.e. 

```javascript
minigrid('#grid1','.grid-item');
minigrid('#grid2','.grid-item');
```

If you're using the version > v1.4.2  you can do that.

By the way, I'd love to see what you're building. I'm going to add a showcase section 😃

Cheers!

**Comment by jodyheavener** [comment]
Hey Henrique!

No problem if we don't want to use it 😀

I've done it this way for two reasons:

* Minigrid will be used on an arbitrary number of container elements, who don't have IDs (though I agree, it wouldn't be hard to add them)
* I'm using Minigrid in a Backbone view, who's element I already have a variable for, so it's less expensive for me to pass in the Node instead doing another QSA

Thanks for the reply! I'll be sure to follow up when this project I'm working on is complete.

**Comment by henriquea** [comment]
Hey @jodyheavener

It does make sense because I'm also using it in a React component. Can you submit a PR please? It's a small change with little impact and big win. 

Looking forward for see this in action 😃

**Comment by henriquea** [comment]
@jodyheavener can you also update the README too? 😃 leave the `gh-pages` for now because I'm working on it then I'll get the content from the README on master.

Cheers

**Comment by jodyheavener** [comment]
Sure!

One thing: I am unable to run test/build. I installed browserify and testling but when I run `npm run test` I get:

```
> minigrid@1.5.0 build /repositories/minigrid
> npm run test && npm run uglify


> minigrid@1.5.0 test /repositories/minigrid
> browserify test.js | testling | tap-spec

sh: tap-spec: command not found
No headless browser found.
```

Any ideas?

Side not: I noticed `browserfy` is spelled incorrectly in CONTRIBUTING.md  ;)

**Comment by henriquea** [comment]
@jodyheavener oh yes sorry you need install also tap-spec `npm install tap-spec` although I can see it on package.json. Thanks for that I'm going to fix it

**Comment by jodyheavener** [comment]
My bad, didn't run npm install

**Comment by henriquea** [comment]
Done! [v1.6.0](https://github.com/henriquea/minigrid/releases/tag/v1.6.0)

Thanks @jodyheavener!

**Comment by jodyheavener** [comment]
:smile_cat:
