### ISSUE TITLE
How to call minigrid with ajax load more button

### ISSUE THREAD

**Issue by Mustafaoeztuerk** [henriquea/minigrid#17]
I have image page and i want to use minigrid plugin but when i click load more button then all new images will be meeting in the upper left corner. It looks i need to call the minigrid function. Anyone can help me how can i call that function ?

$('body').on("click", '.nextphotos', function() {
    var ID = $(this).attr("id");
    var P_ID = $(this).attr("rel");
    var URL = $.bs_url + 'more_photos.php';
    if (ID) {
      $.ajax({
        type: "POST",
        url: URL,
        data: dataString,
        cache: false,
        beforeSend: function() {
          $(".loader").fadeIn(200);
        },
        success: function(html) {
          $("div.images").append(html).each(function() {});
          $("#more" + ID).remove();
        }
      });
    } else {
      $("#more").html('The End');
    }
    return false;
  });

**Comment by henriquea** [comment]
Yes, every time you append anything in the content you have to call the minigrid function again. In your case you want to call it after the `$("div.images").append(html).each(function() {});`

**Comment by Mustafaoeztuerk** [comment]
@henriquea 
Can you explane me. You mean i need to call this function:

(function() {
  minigrid('.grid', '.grid-item');
  window.addEventListener('resize', function() {
    minigrid('.grid', '.grid-item');
  });
})();

like this:

$("div.images").append(html).each(function() {});
minigrid();

**Comment by henriquea** [comment]
Yes! Call minigrid but pass the parameters again e.g.

```javascript
...
$("div.images").append(html).each(function() {});
minigrid('.grid', '.grid-item');
```

**Comment by Mustafaoeztuerk** [comment]
![screen shot 2015-08-09 at 00 20 09](https://cloud.githubusercontent.com/assets/7026443/9152334/73f6911c-3e2c-11e5-9aad-ab97111d0a47.png)

@henriquea i still tryed it before and now it is again same problem here. See screenshot

**Comment by Mustafaoeztuerk** [comment]
@henriquea  When i click load more button then it looks like this. All new images will be meeting in the upper left corner.

![screen shot 2015-08-09 at 00 20 09](https://cloud.githubusercontent.com/assets/7026443/9152343/dc98b880-3e2c-11e5-9fac-2144cafb16c2.jpg)


$('body').on("click", '.nextphotos', function() {

    var ID = $(this).attr("id");
    var P_ID = $(this).attr("rel");
    var URL = $.bs_url + 'more_photos.php';
    if (ID) {
      $.ajax({
        type: "POST",
        url: URL,
        data: dataString,
        cache: false,
        beforeSend: function() {
          $(".loader").fadeIn(200);
        },
        success: function(html) {
          $("div.images").append(html).each(function() {});
          minigrid('.grid', '.grid-item');
          $("#more" + ID).remove();
        }
      });
    } else {
      $("#more").html('The End');
    }
    return false;
  });
  minigrid('.grid', '.grid-item');

**Comment by henriquea** [comment]
@Mustafaoeztuerk I know why. This would be a new feature I have to change something here.

**Comment by Mustafaoeztuerk** [comment]
@henriquea means i can not use minigrid.min.js for now ?

**Comment by henriquea** [comment]
@Mustafaoeztuerk bare with me 😊

**Comment by Mustafaoeztuerk** [comment]
@henriquea I am still here for you.

**Comment by henriquea** [comment]
@Mustafaoeztuerk actually, I just made a test here and this is already working http://output.jsbin.com/kilolu it might be something else in your code?

**Comment by Mustafaoeztuerk** [comment]
@henriquea  It's really simple to understand. An amazing achievement. I wish you success in signing more beautiful.

**Comment by henriquea** [comment]
Thanks @Mustafaoeztuerk for the nice words! I wish I got $1 for each star here LOL! I'm glad this is being useful and people are using it. If you can please feel free to share the work when you finish 😊

**Comment by henriquea** [comment]
@Mustafaoeztuerk shall I close this issue?

**Comment by Mustafaoeztuerk** [comment]
@henriquea  so one more question here. When when i reload the page sometimes amassing some images overlap like the screenshot.

![screen shot 2015-08-09 at 01 55 29](https://cloud.githubusercontent.com/assets/7026443/9152681/07e110a2-3e3a-11e5-95d8-481d47aea257.jpg)

What can cause this ?

**Comment by henriquea** [comment]
Hard to know without proper debug but I'd suggest you to add a setTimeout of 50ms after  append your items, before you call minigrid again.

**Comment by henriquea** [comment]
I'm doing an example loading 90 items and I didn't have any issues like that.

**Comment by Mustafaoeztuerk** [comment]
But I can show you a screenshot. I tryed setTimeout and it will come again sometimes. If you want to see real this issue please add me on facebook. https://www.facebook.com/matsocial

**Comment by Mustafaoeztuerk** [comment]
So ok i will show you the problem here. Please click this link : http://jsfiddle.net/mustafaozturk74/fdjsj7wo/

The problem will come sometimes. Hence please try several times.

**Comment by henriquea** [comment]
@Mustafaoeztuerk if you read my comment here https://github.com/henriquea/minigrid/issues/16#issuecomment-129043843 this happens because the image is being loaded and it isn't possible to calculate the grid item width and height if so. What you need  is a lazy load for the images. Make sure all images are loaded before call again minigrid. The rule applies if you're using any other grid library.

The comment above has one example.

**Comment by tunnckoCore** [comment]
@Mustafaoeztuerk just async nature of js

as @henriquea said, add set timeouts even to zero like `setTimeout(grid, 0)`

```js
(function($){
  
  function grid() {
    minigrid('.grid', '.grid-item');

  }
  
  function loadMore() {
    $('.grid').append('<div class="grid-item b" ><img src="http://img005.lazygirls.info/people/tamanna_bhatia/tamanna_bhatia_tamanna_latest_images_7_jpg_jpeg_image_1024_1226_pixels_scaled_76__qWkMn2nO.sized.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://www.wired.com/wp-content/uploads/2014/12/9-credit-1.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://2.bp.blogspot.com/-ot4eLEDWAjs/Uk9fzDJlQCI/AAAAAAAAKsU/UfUhYvEvAz4/s1600/Recherche-image-b%C3%A9b%C3%A9-80.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://g-ecx.images-amazon.com/images/G/01/electronics/detail-page/Klipsch-Image-S4-II-Black-Lifestyle.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://www.technobuffalo.com/wp-content/uploads/2015/01/neytiri-avatar-5824.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://www.trendfilm.com/uploads/film/2015/02/avatar-trend-film-718.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://www.hdwallpapers.in/walls/jake_sully_avatar_disguise-wide.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://i.ytimg.com/vi/nbH-4owbhX4/maxresdefault.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://cdn.wegotthiscovered.com/wp-content/uploads/DreamWorks-Animation-HOME-1-640x360.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://www.iknowtoday.com/wp-content/uploads/2015/03/27-660x330.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://img005.lazygirls.info/people/tamanna_bhatia/tamanna_bhatia_tamanna_latest_images_7_jpg_jpeg_image_1024_1226_pixels_scaled_76__qWkMn2nO.sized.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://www.wired.com/wp-content/uploads/2014/12/9-credit-1.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://2.bp.blogspot.com/-ot4eLEDWAjs/Uk9fzDJlQCI/AAAAAAAAKsU/UfUhYvEvAz4/s1600/Recherche-image-b%C3%A9b%C3%A9-80.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://g-ecx.images-amazon.com/images/G/01/electronics/detail-page/Klipsch-Image-S4-II-Black-Lifestyle.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://www.technobuffalo.com/wp-content/uploads/2015/01/neytiri-avatar-5824.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://www.trendfilm.com/uploads/film/2015/02/avatar-trend-film-718.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://www.hdwallpapers.in/walls/jake_sully_avatar_disguise-wide.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://i.ytimg.com/vi/nbH-4owbhX4/maxresdefault.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://cdn.wegotthiscovered.com/wp-content/uploads/DreamWorks-Animation-HOME-1-640x360.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://www.iknowtoday.com/wp-content/uploads/2015/03/27-660x330.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://img005.lazygirls.info/people/tamanna_bhatia/tamanna_bhatia_tamanna_latest_images_7_jpg_jpeg_image_1024_1226_pixels_scaled_76__qWkMn2nO.sized.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://www.wired.com/wp-content/uploads/2014/12/9-credit-1.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://2.bp.blogspot.com/-ot4eLEDWAjs/Uk9fzDJlQCI/AAAAAAAAKsU/UfUhYvEvAz4/s1600/Recherche-image-b%C3%A9b%C3%A9-80.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://g-ecx.images-amazon.com/images/G/01/electronics/detail-page/Klipsch-Image-S4-II-Black-Lifestyle.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://www.technobuffalo.com/wp-content/uploads/2015/01/neytiri-avatar-5824.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://www.trendfilm.com/uploads/film/2015/02/avatar-trend-film-718.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://www.hdwallpapers.in/walls/jake_sully_avatar_disguise-wide.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://i.ytimg.com/vi/nbH-4owbhX4/maxresdefault.jpg"/></div>');
    $('.grid').append('<div class="grid-item b"><img src="http://cdn.wegotthiscovered.com/wp-content/uploads/DreamWorks-Animation-HOME-1-640x360.jpg"/></div>');
    $('.grid').append('<div class="grid-item b" ><img src="http://www.iknowtoday.com/wp-content/uploads/2015/03/27-660x330.jpg"/></div>');
    setTimeout(grid,0)
  }
  
  function ajax() {
    // fake request
    setTimeout(loadMore,0);
  }
  
  $('.button').on('click', function(e){
    e.preventDefault();
    ajax();
  });
  
  grid();
  
})(jQuery);
```

**Comment by henriquea** [comment]
Thanks @tunnckoCore 50 is my favourite number for this cases 😀

@Mustafaoeztuerk I'm closing this issue but feel free to drop any extra comment here.

Cheers!
