### ISSUE TITLE
Error with "npm run test"

### ISSUE THREAD

**Issue by peduarte** [henriquea/minigrid#19]
Not able to run `npm run test` successfully.

**I have installed the following:**
```
npm install -g browserify
npm install -g testling
```
**Result:**
<img width="405" alt="screenshot 2015-08-19 17 14 27" src="https://cloud.githubusercontent.com/assets/372831/9361935/c935e274-4695-11e5-9167-28d320887ee8.png">

The error is: *No headless browser found.*

Anyone else experiencing this?

Update: my co-worker just tried on his machine and is getting the same error.

Update 2: This could be related to the issue https://github.com/substack/testling/issues/111

**Comment by henriquea** [comment]
Hmmm I might have one clue but will investigate tonight.

**Comment by peduarte** [comment]
Temporary quick fix

After installing phantomjs via homebrew...
```
rm -rf ~/.config/browser-launcher
```

For some reason, this works. 
But still, crap fix.

💩

/cc https://github.com/substack/testling/issues/111

**Comment by henriquea** [comment]
ping @rafaelrinaldi

**Comment by rafaelrinaldi** [comment]
@peduarte @henriquea `testling` was not listed as a dependency. I've fixed and improved this and made a PR #20.

Please let me know if something has to be modified in order for the PR to be accepted/valid. I'm in a hurry right now.

Thanks!

**Comment by peduarte** [comment]
@rafaelrinaldi 
I manually made the updates from your PR, and the tests ran successfully, but only after installing `phantomjs`.

Seems that `phantomjs` is a dependency. Might be worth making a note of that.

:beers:

**Comment by rafaelrinaldi** [comment]
@peduarte Hum, that doesn't make much sense. I have quite a few libraries that rely on `tape-run` for CI and I have never pointed PhantomJS as a dependency. You know that you can specify a browser via `-b`. Maybe the default behavior is to look up for a local PhantomJS binary, but I'm not sure.

I'm going to dig deeper into this later, will update you guys when I find something useful.

In the meantime @henriquea can :rocket: because CI will work.

**Comment by rafaelrinaldi** [comment]
So, yeah `tape-run` does rely on a local copy of PhantomJS. It uses `browser-run` in the background which points this out on the docs:

> Defaults to phantom. Available if installed (...)

I think that the simplest way of fixing this is to specify PhantomJS as a dev dependency. I just sent a commit which locks on version `1.9.2-6`.
I've removed my local PhantomJS binary, installed the dependencies, ran the test suite and everything went smooth. Thanks @peduarte @henriquea :+1:

**Comment by peduarte** [comment]
@rafaelrinaldi @henriquea happy days! :tada: :balloon:

**Comment by henriquea** [comment]
Good stuff guys! Thanks @rafaelrinaldi and @peduarte I'll look into this when I get home later 👌🏼
