### ISSUE TITLE
Text & Image overflow

### ISSUE THREAD

**Issue by OmarElGabry** [henriquea/minigrid#21]
I need to put images along with text, header, ..etc. in each ```.grid-item```(with fixed width), I encountered some problems as text & image overflow, images don't fit correctly, and so forth.

I played around the examples provided in the Demo, and I came across quick solution for now, please [check it](http://jsbin.com/juruwezala/1/edit?html,output) and let me know if you have a better implementation for using images, text, headers within each ```.grid-item```

**Comment by henriquea** [comment]
@OmarElGabry I'm not sure what you mean by overflow. The behaviour in the example you sent is the correct one, the image width is higher than the container. If you're looking into how to fit the image in the `.grid-item` just do:

```css
.grid-item img {
  width: 100%;
}
```

[jsbin](http://jsbin.com/bayiqoxeda/1/edit?css,output)

**Comment by OmarElGabry** [comment]
I mean content(whether text or image) overflows an element's box vertically and/or horizontally, 

Yes, the image width is higher than the container, I guess the best way to handle this is to restrict the width say ```250px```, and ```overflow: hidden;``` because ```width: 100%;``` will make the image stretched horizontally.

Thanks!

**Comment by henriquea** [comment]
If you're content has `position: relative;` to all elements I can't see this happening. The example you sent looks right for me or I'm missing something here.

**Comment by OmarElGabry** [comment]
Yes, It works as well. I was asking if you have a better implementation in mind, maybe you've tested under different circumstances. But, if you don't see any problem, that's fine.

If you can also add to the documentation on how to use images and text within ```.grid-item``` It would be better because usually people will add some content inside each.

Regarding if the content has ```position: relative;```, each ```.grid-item``` will still fill the horizontal space, maybe I misunderstood you.

Anyways, here is what i've done:
1. Implementation in [Demo](http://jsbin.com/maroda/9/edit?html,css,output)
2. What happened when I added images and text [Overflow](http://jsbin.com/jusesuvami/edit?html,css,output)
3. Then, I added ```display: inline-block;```, ```overflow: hidden;``` and removed ```height: 120px;``` [Fixed](http://jsbin.com/vusowopamu/1/edit?html,css,output)

**Comment by henriquea** [comment]
@OmarElGabry 

> If you can also add to the documentation on how to use images and text within .grid-item It would be better because usually people will add some content inside each.

I didn't add anything because this is something implicit no? I mean the whole "cards" concept is that you would have content inside the items. I tried to keep the demo as simple as possible, still people get confused 😂

> Regarding if the content has position: relative;, each .grid-item will still fill the horizontal space, maybe I misunderstood you.

Oh if you mean fill the page/container width you can fix that by adding `max-width` to your `.grid` container.

I'm closing this issue, feel free to add further comments here.

Cheers 🍺
