### ISSUE TITLE
query direct children is not supported by querySelector(All) 

### ISSUE THREAD

**Issue by soenkekluth** [henriquea/minigrid#23]
to target all direct children of the container without a specific class is not well supported by ``querySelector``

to get all children - the only way I know of is to use the :scope pseudoselector - but thats not supported by our friend IE for example

``.querySelectorAll(":scope > article, :scope > div");``

https://developer.mozilla.org/en-US/docs/Web/CSS/:scope

maybe a solution would be to make `itemSelector` either a string = selector or an array of elements?

**Comment by TrySound** [comment]
@soenkekluth https://github.com/lazd/scopedQuerySelectorShim

**Comment by soenkekluth** [comment]
@TrySound thanks for that. but maybe its worth a thought because gridContainer can also be a node or a query string.

**Comment by TrySound** [comment]
And what problem?

**Comment by soenkekluth** [comment]
no problem at all. just checking befor PR

**Comment by soenkekluth** [comment]
ps.. polyfill that throws errors that way... ;) no usw for that.

````
if (!HTMLElement.prototype.querySelectorAll) {
    throw new Error('rootedQuerySelectorAll: This polyfill can only be used with browsers that support querySelectorAll');
  }
````

**Comment by TrySound** [comment]
@soenkekluth You want to support so old browsers?

**Comment by henriquea** [comment]
Hi @soenkekluth I'm trying to think here the use case for scope! As @soenkekluth pointed you can always use a shim. The `querySelectorAll` has a good support of course not including IE8. I don't have any intention in support IE8 anyway.

**Comment by soenkekluth** [comment]
@TrySound its not only old but mobile browsers:
![2015-09-02 04 46 32 pm](https://cloud.githubusercontent.com/assets/201338/9634482/3e0ed720-5192-11e5-847d-79d9ea524ab6.png)
see https://developer.mozilla.org/en-US/docs/Web/CSS/:scope

**Comment by soenkekluth** [comment]
@henriquea 
its just about beeing independent from the class selector.

````
.grid {
  
  > article,
  > aside,
  > section,
  > div,
  > li {

    float: left;
    width: 33.3%;
    ...
  }
}
````

**Comment by TrySound** [comment]
@soenkekluth Shim will throws an error for browsers that do not support querySelector at all! And it successfully shims normal browsers.

**Comment by soenkekluth** [comment]
@TrySound yeah - not a good design... will PR maybe...

**Comment by TrySound** [comment]
@soenkekluth What is wrong? I don't understand. If querySelector doesn't exists it still will be thrown 'undefined is not a function'.

**Comment by soenkekluth** [comment]
@TrySound no - only true by design. 
if you wrap the whole polyfill inside an `if (HTMLElement.prototype.querySelectorAll) {....}` that would not be the case. same as if you just `return;` instead of throwing an error.

a polyfill should not in any cause (throw) an error that won't be catched by the polyfill itself. one who uses that polyfill has to do it in a try block so it won't crash his app.

**Comment by TrySound** [comment]
Okay.

**Comment by henriquea** [comment]
@soenkekluth ok but then we're talking about `scope` and not querySelector or I'm missing something here. I'm still wondering how much people would use the scope.

**Comment by soenkekluth** [comment]
@henriquea well since gridContainer can be a query string or a DOM node I could also expect the gridElements to be - don't you think? even more: I would expect if gridElements (in this case 'itemSelector') is undefined - the direct children of gridContainer would be targeted. wouldn't you?

**Comment by henriquea** [comment]
@soenkekluth it does make sense. What are you proposing then?
