### ISSUE TITLE
Text rendering issues in Chrome

### ISSUE THREAD

**Issue by 3oheme** [henriquea/minigrid#26]
First of all, congrats! great plugin and clever new approach using translate3D instead of just absolute positioning.

The issue is related to text and font rendering. The elements that are further from the top left position will have blurry text. 

This is an horizontal slice of my card layout, with the plugin already triggered:

![full-width](https://cloud.githubusercontent.com/assets/725114/9956660/c428defe-5dfa-11e5-9b31-000004379f52.png)

To check the issue in detail, I did the following:
* Grabbed a screenshot with Photoshop,
* Created a new layer and aligning the cards on top,
* And toggled the element on and off
In the following GIF it's clearly visible the issue:

![blurry-text](https://cloud.githubusercontent.com/assets/725114/9956701/0a092bea-5dfb-11e5-8211-ac9abad4e795.gif)

I guess that this is related to Chrome creating a "texture" with each card bitmap to do the translate3D, so changing this would probably require a different whole approach, but maybe there's some magic sort-of `-webkit-perspective: 1000;` that could may fix it :-P

Environment: to Chrome 45.0.2454.93 (64-bit) in a 13 inches late 2011 Macbook.

**Comment by henriquea** [comment]
Hey @3oheme thanks for nice words. I'm glad people are using it. Could you share the link as well? I'm building a new page design and want to add some showcases.

So regarding your issue it would be nice to see the live example so I can play on dev tools. You could DM me on Twitter @healves82 or email henriquea@gmail.com? If this is not possible you could try to add to your `.grid-item` the follow `transform: perspective(1px)` but I might need to add it in the library as well.

Let me know please 😊

**Comment by peduarte** [comment]
If you could replicate the issue in its simplest form using [jsbin](http://jsbin.com) or something, I can help take a look.

**Comment by 3oheme** [comment]
Hi guys! I'm back from the weekend :-) I'm pretty busy this week, but I'll try to find some time.

Cheers,

**Comment by henriquea** [comment]
Looking forward @3oheme let me know if we can help.

**Comment by henriquea** [comment]
Hey @3oheme any update on this? Cheers

**Comment by henriquea** [comment]
Hey @3oheme can I close this issue? Have you found the solution?

**Comment by henriquea** [comment]
@3oheme this https://github.com/henriquea/minigrid/blob/master/src/index.js#L111 should fix it.

**Comment by peduarte** [comment]
@henriquea I think he forgot about this 😂

**Comment by henriquea** [comment]
@peduarte yup a bit annoying tbh since I was expecting a link to see the problem in action 😃

**Comment by flystyle** [comment]
So the best solution for me in order to fix this blurry effect was to add this simple line of code:
`-webkit-filter: blur(0);`
There is also a known bug that only affects retina screens. So in order to make it works also for retina, I recommend to add this second line:
`-webkit-transform: translateZ(0);`
