### ISSUE TITLE
zero default gutter

### ISSUE THREAD

**Issue by TrySound** [henriquea/minigrid#28]
Hi, Henrique!

I use minigrid on adaptive/responsive sites. Grid should be fluid. But gutters computing wasn't so expected with percentage values. I found the solution like in bootstrap grid with padding and box-sizing. It would be good to set more meaningful default gutter value in the next major version.

[Here's example](http://leravalera.ru/beta/illustration)

**Comment by henriquea** [comment]
Hey @TrySound that's a good idea. I'm working on the next version v2 as you can see 😊 I was thinking in use `rem` rather pixels. Feel free to drop a gist with a suggestion.

**Comment by TrySound** [comment]
@henriquea Why gist?

**Comment by henriquea** [comment]
@TrySound or PR just because I'm in the middle of v2 right now

**Comment by henriquea** [comment]
I think the `rem` with fallback to `em` or `px` will sove the issue. Will do a few tests to see here.

**Comment by TrySound** [comment]
@henriquea I'm not sure non-persentage units have a sense here. Just fixed unit algo won't work with persentage units.

**Comment by henriquea** [comment]
@TrySound np! That PR is too big. I'm going to hold on. I'm almost done here with v2 after merge to master we can tackle this gutter issue ok?

Cheers

**Comment by TrySound** [comment]
Ok

**Comment by henriquea** [comment]
@TrySound this is done on [v2.1.3](https://github.com/henriquea/minigrid/releases/tag/v2.1.3) 

Thanks 🍺

**Comment by TrySound** [comment]
@henriquea Thanks. But for the future strict semver let's use modules safely. Else we receive many fails and broken sites.

**Comment by henriquea** [comment]
@TrySound yup it was a mistake I realised after hit the release button.
