### ISSUE TITLE
position: absolute required for grid items

### ISSUE THREAD

**Issue by bolatovumar** [henriquea/minigrid#3]
'position: absolute' seems to be required for grid items in order for everything to work. However, this is not mentioned anywhere in the readme.md or the demo site. It becomes pretty obvious after inspecting the demo in the devtools but might confuse some people to a degree so that they would not use the library.

A simple solution would be to specifiy 'position: absolute' in JavaScript since the functionality depends on it.

**Comment by henriquea** [comment]
@bolatovumar yes! It does make sense. I was thinking about it this weekend. Also I'm doing to add the `position:relative` to the main container as well. I'm going to merge your branch later today. 

Thanks!
