### ISSUE TITLE
Safari onload

### ISSUE THREAD

**Issue by TrySound** [henriquea/minigrid#36]
Don't you think this detect is better? Caz `webkit` also work on chrome.
https://github.com/henriquea/minigrid/blob/master/src/index.js#L51
```js
/safari/i.test(navigator.userAgent.toLowerCase())
```

**Comment by henriquea** [comment]
@TrySound in this case the webkit prefix is right because both have `document.readyState` `window.onload` is problematic on both.

**Comment by TrySound** [comment]
@henriquea You sure? I never heard about this problem on chrome.

**Comment by TrySound** [comment]
@henriquea Also I think the better way to define onload is addEventListener.

**Comment by henriquea** [comment]
@TrySound I did a bit of investigation before. I had issues with `window.addEventListener('load')` not being fired on Chrome or Safari in the first time the page was loaded. You can find loads of discussion on StackOverflow about this issue. Anyway, I agree with you and shall revise this bit of code soon.

**Comment by TrySound** [comment]
@henriquea Okay, but if you use custom onload, u can use addEventListener for other browsers which works fine.

**Comment by henriquea** [comment]
Fixed on [v2.2.0](https://github.com/henriquea/minigrid/releases/tag/v2.2.0)
