### ISSUE TITLE
Bad minification

### ISSUE THREAD

**Issue by TrySound** [henriquea/minigrid#38]
Did you see that minified file greater than index.js? Seems like webpack do not minified it, just stringified and added to eval (what?).

**Comment by henriquea** [comment]
Hmm, really? Webpack is using uglify so it should work. I'll double check

**Comment by TrySound** [comment]
@henriquea Seems like it doesn't work well out of the box.

**Comment by TrySound** [comment]
@henriquea And uglify do not wrap code in eval.

**Comment by henriquea** [comment]
@Try also the lib isn't 2kb anymore. This is bad. I'm going to review it and see what can be simplified.

**Comment by TrySound** [comment]
@henriquea Okay :)

**Comment by henriquea** [comment]
Fixed on [v2.2.0](https://github.com/henriquea/minigrid/releases/tag/v2.2.0)

**Comment by TrySound** [comment]
Cool!
