### ISSUE TITLE
Links to CDN & Changelog broken

### ISSUE THREAD

**Issue by alexduncan** [henriquea/minigrid#39]
On the minigrid homepage (http://alves.im/minigrid/) there are two broken links:

  +  CDN hosted version of minigrid (cdnjs.cloudflare.com/ajax/libs/minigrid/2.0.0/minigrid.min.js)
  +  CHANGELOG https://github.com/henriquea/minigrid/CHANGELOG.md

**Comment by tunnckoCore** [comment]
yep :+1: 

It seems @henriquea's automation is broken lol.

I noticed that few times before v2 and he lastly updated to 2.0.0 but few hours/days after that new version came and .. yea. :D

**Comment by henriquea** [comment]
Thanks @alexduncan and @tunnckoCore the problem is that cndjs takes ages to update so even if I put it automatically it won't reflect in the cdn 😞 I'll update this when I have some spare time this week.

**Comment by henriquea** [comment]
Talking with @rafaelrinaldi we're keen to remove it from the CDN because the releases are always faster than their update. In 90% of the cases I believe you would bundle minigrid and in the last case you can always download the minified version from GitHub. 

Thoughts? @rafaelrinaldi

**Comment by henriquea** [comment]
Latest version is on [npmcdn](https://npmcdn.com/minigrid@3.0.1/dist/minigrid.min.js).

**Comment by tunnckoCore** [comment]
:+1: add it to readme and the site :)

Also the BrowserifyCDN is good alternative https://www.brcdn.org/?module=minigrid&version=list (currently something is broken I don't know why)

**Comment by henriquea** [comment]
@tunnckoCore I added it on http://alves.im/minigrid/ cool! Didn't know about brcdn.
