### ISSUE TITLE
Not working on demand when loaded via requirejs

### ISSUE THREAD

**Issue by alexduncan** [henriquea/minigrid#40]
We pull minigrid using bower and include it using requirejs.

I have tried to recreate the situation in this JSBin:
http://jsbin.com/zepufe/edit?js,console,output

It appears to be failing because `loaded` is undefined on [line 45](https://github.com/henriquea/minigrid/blob/master/src/index.js#L45) causing the script to add event listeners for the `load` event which has already passed.

Thanks very much for your hard work creating minigrid, we find this little library very useful :+1:

**Comment by henriquea** [comment]
@alexduncan hmm ok I'm using with React so it should flag something as well. I'll investigate. Thanks for the hands up man!

**Comment by alexduncan** [comment]
@henriquea thanks very much. Look forward to hearing back :-)

**Comment by henriquea** [comment]
@alexduncan sorry for the delay. Have been sunk in work the past two months. Yes, I know where the problem is. As I mentioned here https://github.com/henriquea/minigrid/issues/43#issuecomment-166740954 I'm going to remove the load listener which is causing some bad side effects.

**Comment by henriquea** [comment]
@alexduncan just released the `v3.0.0` which should address this issue 👍

[CHANGELOG](https://github.com/henriquea/minigrid/blob/master/CHANGELOG.md#v300)
