### ISSUE TITLE
Ajax appended items

### ISSUE THREAD

**Issue by phil-bauch** [henriquea/minigrid#41]
First of all thanks for this great piece of work, works like a charme. Anyway, there's one item I have.

My goal is, to load a certain number of cards and the (byClick or scroll) append new cards. Basically it works, but when the new  cards are added, and I call grid() again, logically all cards are animated again. Is there any way just to animate the new cards in? When having a long list of cards, the performance decreases a lot (logically, of course)

Thanks and greetings from Spain,
Phil

**Comment by henriquea** [comment]
Hey @phil-bauch thanks and sorry for the delay! 

Just don't append the items in the same container. I'd create a new container for each pagination e.g.

```html
<div id="page1" class="grid">
  <div class="grid-item"></div>
</div>

<div id="page2" class="grid">
  <div class="grid-item"></div>
  ...
</div>
```

The do something like this:

```js
var props = {
 container: '#page1',
 item: '.grid-item',
 gutter: 6
};

var minigrid = minigrid(props);
// when paginate
props.container = '#page2';
minigrid(config);
```

Cheers
