### ISSUE TITLE
Add percent width or cols calculation

### ISSUE THREAD

**Issue by Tusko** [henriquea/minigrid#42]

**Comment by TrySound** [comment]
@Tusko Just do not add gutters and percents will work

**Comment by TrySound** [comment]
@Tusko See example http://leravalera.ru/beta/illustration

**Comment by henriquea** [comment]
Hey @Tusko, I think @TrySound answer your question? 

Thanks again @TrySound!

**Comment by Tusko** [comment]
@henriquea @TrySound hey!
sorry, I forgot to answer.
It works fine ;) thank you

**Comment by phil-bauch** [comment]
Sorry for my delayed answer, too and thanks for the nice work! Love it and will post a link to my site when its all done

**Comment by henriquea** [comment]
No worries! Cheers guys 🍻
