### ISSUE TITLE
Doesn't work with many selectors

### ISSUE THREAD

**Issue by Tusko** [henriquea/minigrid#43]
Hi! I have many grids at one page, so tried this:

    minigrid({
        container: '.minigrid',
        item: '.grid-item'
    });

The first grid container works fine, but all next containers doesn't work.
Can you @henriquea help me with that?

**Comment by TrySound** [comment]
@Tusko Can you reproduce minimal markup ?

**Comment by Tusko** [comment]
@TrySound Hi)
Full markup here
http://npdinternational.com/biophysics-news/

Inside sections `.categorize` -> `.cat-grid > .cat-item`

I have changed selectors now)

**Comment by TrySound** [comment]
@Tusko I understood. It's not iterate selectors. You can use this recipe
```
[].forEach.call(document.querySelectorAll('.grid'), function (container) {
  minigrid({
    container: container,
    item: '.grid-item'
  })
})
```

**Comment by Tusko** [comment]
@TrySound something strange. 
When I have started your code from firebug console - all works fine.
When started in my code - doesn't work.
Trying to understand what is it(

**Comment by Tusko** [comment]
I have created function

    function iamgrid(){
        [].forEach.call(document.querySelectorAll('.cat-grid'), function (container) {
            minigrid({
                container: container,
                item: '.cat-item'
            });
        });
    }

When I put it inside `$(document).ready(function(){ /* function here */ });` or `$(window).load(function(){ /* function here */ })` - function not started.
When I put function outside `.ready` or `.load` - function works, but doesn't work on resize.

**Comment by henriquea** [comment]
@Tusko I'll remove the load listener from minigrid which is causing other issues. The way I see today is that minigrid shouldn't care if the document is ready or not and leave it to the user. Hopefully I'll have some spare time this holidays to take care of it.

**Comment by TrySound** [comment]
@henriquea  :+1:

**Comment by henriquea** [comment]
Btw thanks for the help @TrySound 👊

**Comment by rafaelrinaldi** [comment]
FYI the solution I've proposed on the PR #45 could solve this in a more elegant way. See the example.

**Comment by henriquea** [comment]
@Tusko the `v3.0.0` was released and should address this issue 👍
