### ISSUE TITLE
Doesn't work in  MS EDGE

### ISSUE THREAD

**Issue by Tusko** [henriquea/minigrid#44]
Hi guys. When site is cached - minigrid doesn't work in EDGE.

Try it here http://dev.cs.lviv.pro/optshop/shop/
Open shop, go to about page, then go back to shop from menu.

**Comment by NicolasParada** [comment]
It actually works for me...

**Comment by henriquea** [comment]
I believe this is related with #40 and the other issues regarding the loading event.

**Comment by Tusko** [comment]
@NicolasParada @henriquea I have created video https://goo.gl/HMqa4f

**Comment by NicolasParada** [comment]
Nope, I can't reproduce it. 
It works fine for me.

**Comment by Tusko** [comment]
ok. 
temporary fix


    if($('body').hasClass('fuck-you-edge')) {
        setTimeout(function(){
            iamgrid();
        }, 1e3);
    }

:D
