### ISSUE TITLE
minigrid does not work in single page apps

### ISSUE THREAD

**Issue by jamesfzhang** [henriquea/minigrid#46]
I'm building a SPA using React with React Router. I'm experiencing a problem where navigating to a page using minigrid doesn't trigger the `init` function since this isn't a fresh pageload. Here's the line of code that causes this issue: https://github.com/henriquea/minigrid/blob/master/src/index.js#L51

**Comment by jamesfzhang** [comment]
Nevermind, I didn't see the `skipWindowOnLoad` property. Thanks!

**Comment by henriquea** [comment]
@jamesfzhang yes, we're going to remove it hopefully this weekend. Minigrid shouldn't care about the DOM being loaded or not.
