### ISSUE TITLE
API refactoring

### ISSUE THREAD

**Issue by henriquea** [henriquea/minigrid#47]
@rafaelrinaldi we need simplify the API mainly getting rid of the `onLoad` event https://github.com/henriquea/minigrid/blob/master/src/index.js#L55 which causing a lot of issues.

Minigrid shouldn't care if the DOM is loaded or not, let's leave this up to the user. I'm thinking in something like `minigrid().init(props)` and I guess have a `update` method would be handy too.

Thoughts?

**Comment by joaocunha** [comment]
:+1:. Also, the `init` function could be split into other minor functions.

**Comment by alexduncan** [comment]
:+1:  @henriquea sounds like a good idea.

@joaocunha What are you thinking? Surely better to just keep simple `init` & `update` functions and make it idempotent?

**Comment by rafaelrinaldi** [comment]
Yup, I also think that minigrid shouldn't care about how/when to mount. Will try to tackle this over the weekend :v:

**Comment by henriquea** [comment]
The `v3.0.0` was released 🎉 🎈

[CHANGELOG](https://github.com/henriquea/minigrid/blob/master/CHANGELOG.md#v300)
