### ISSUE TITLE
What about class 'loaded' after init?

### ISSUE THREAD

**Issue by Tusko** [henriquea/minigrid#49]

**Comment by henriquea** [comment]
@Tusko anything regarding loading was removed. Also if you are using minigrid with React adding a class from minigrid wouldn't work at all. For this purpose you can use the `done` callback.

```js
new Minigrid({
  container: '.cards',
  item: '.card',
  gutter: 6,
  done: function() {
    var container = document.querySelector('.cards');
    container.classList.add('loaded');
  }
}
```

**Comment by henriquea** [comment]
@Tusko closing this issue but feel free to comment again if you need ok 👍
