### ISSUE TITLE
Multiply grid

### ISSUE THREAD

**Issue by alexeymanoylo** [henriquea/minigrid#51]
Hi, there is a possibility on the same page to create multiple versions of the grid?
Now it seems this can not be done.

**Comment by TrySound** [comment]
@alexeymanoylo `container` and `item` option can be element objects like `document.querySelector('.container');`

**Comment by henriquea** [comment]
@alexeymanoylo closing this issue since @TrySound have answered it. Please feel free to ask anything else ☺️
