### ISSUE TITLE
Is there a way to make the grid work on RTL languages?

### ISSUE THREAD

**Issue by dommariano** [henriquea/minigrid#59]
On LTR languages, we get the grid to start from the left.  On RTL languages, like Hebrew, I need to know if there is an option to get to this to start laying out items from the right.

**Comment by henriquea** [comment]
Hi @dommariano that's an interesting point. I need to think about this and come back to you later.

**Comment by henriquea** [comment]
Hi @dommariano sorry for the delay. I just added support for RTL in the latest version `v3.1.0`. Just pass the `rtl: true` in the props e.g.

```js
new Minigrid({
  container: '.cards',
  item: '.card',
  gutter: 6,
  rtl: true
});
```
Let me know if you find any issue.

Cheers

**Comment by dommariano** [comment]
Sorry it took almost a year to reply. That is awesome!
