### ISSUE TITLE
Minified version?

### ISSUE THREAD

**Issue by bolatovumar** [henriquea/minigrid#6]
I assume most people who might use this have their own build pipeline which handles minification and all that stuff, but some might not. The might still wanna use a minified file even though the non-minified file is already pretty small.

**Comment by henriquea** [comment]
@bolatovumar yes exactly because the lib is only 2kb I didn't want to add this but I'm ok in add gulp. My main focus is keep it very simple. I'm in a middle of something here and will come back to this later 😊Thanks!

**Comment by bolatovumar** [comment]
I figured it wouldn't hurt since the gulp watch task will automatically
minify all the code as soon as it gets saved with an added bonus of linting.

**Comment by henriquea** [comment]
Yes I agree. It's a win-win!

**Comment by tunnckoCore** [comment]
also because CDNs :) they want mostly only minified versions.

**Comment by henriquea** [comment]
@tunnckoCore @bolatovumar yup CDN is on my todo list. To be honest I was thinking in use webpack because is something I've been using for a while. Didn't know about dush I'll definitely check!

**Comment by peduarte** [comment]
+1 webpack

**Comment by bolatovumar** [comment]
Don't know much about webpack but do know that it's a module bundler similar to Browserify. Since we are not bundling anything here a gulp or grunt solution seems like an obvious choice.

**Comment by peduarte** [comment]
Webpack is much more lightweight than gulp/grunt – it's the perfect tool to take a simple JavaScript file, such as this, and output a minified version of it. 
But of course, gulp/grunt would also accomplish the same task, so I guess it comes down to a matter of preference.

**Comment by tunnckoCore** [comment]
> a gulp or grunt solution seems like an obvious choice.

for minifying? my gash :D just `npm install uglify-js && uglifyjs -m -c -o minigrid.min.js index.js`

stop using gulp everywhere and naming everything `gulp-*` all is just streaming, not needed in cases like this, its overhead. :)

**Comment by henriquea** [comment]
Ta all! I love a warm 🔥 discussion! I agree with @tunnckoCore about just install the uglify then add it to `scripts` in the package.json I'm tweaking a bit the docs page and adding a basic test. Coming back to this later. Cheers!

**Comment by bolatovumar** [comment]
@tunnckoCore's suggestion seems reasonable. I do think that gulp/grunt proved some utility since you don't have to re-run the script for minification yourself. Just run the watch task. I find that I oftentimes forget to do things like minification if I have to run something manually.

**Comment by tunnckoCore** [comment]
> Ta all! I love a warm :fire: discussion!

:laughing: :beers: 

@bolatovumar for thus things there have tons of variants in the wild

npm.im/wtch
npm.im/watch
npm.im/gulp-watch
npm.im/watchify
npm.im/livereload

and etc, i cant remember them lol, `gulp-watch` seems good choice if you so much want "gulp"-ish gnomes. I just hate node-glob and glob-stream. As idea gulp is awesome, implementation sucks - partially because shitty `node-glob` years after years. But soon is coming something really dramatically better, faster and awesome. :)

**Comment by henriquea** [comment]
Done on [v1.4.3](https://github.com/henriquea/minigrid/releases/tag/v1.4.3)

**Comment by peduarte** [comment]
Good solution +1

**Comment by tunnckoCore** [comment]
@henriquea you can remove `./node_modules/.bin/` part, it's not needed when is invoked from `npm scripts` .. stay classy, stay pretty :tropical_drink:

**Comment by henriquea** [comment]
@tunnckoCore it is if you don't have it installed globally?

**Comment by tunnckoCore** [comment]
in my opinion.. as im remembered ;d

**Comment by henriquea** [comment]
@tunnckoCore I rarely install packages globally. It's a good way to go you don't have to force people to install globally as well 😊

**Comment by tunnckoCore** [comment]
Haha. I dont like to force them to wait 5mins to just fix some bug or send some PR. See my `package.json`s, they are so small, clean shine and pretty. Are you seeing anywhere istanbul, test, framerowrks, coverages, standards, lints, hints? Just one `standard && node test.js` - yesshh

I :heart:  them.
