### ISSUE TITLE
Optionally position via top & left

### ISSUE THREAD

**Issue by lukasoppermann** [henriquea/minigrid#60]
Hey,

could you maybe add an option to allow positioning via absolute position and top and left instead of only translate? 

**Reason**
I want to scale items on hover, however, as this plugin already applies a transformation to the cards I cannot do this. This means I need to scale the children and add a `overflow:visible !important;` to not cut of the overflow from scale. However this leads to a weird error in firefox where sometimes the cards are fine and sometimes they are cut off. 

Allowing to scale the main card would fix this issue.

**Comment by henriquea** [comment]
Hey @lukasoppermann is there any way you could provide a jsbin demo? I feel you could achieve the same by using `transform-origin` but it's hard to say exactly without see any stuff 😊

**Comment by lukasoppermann** [comment]
Uhh, sure, @henriquea but is will take a moment. `transform-origin` is for sure not going to solve this issue. Maybe removing the automatically added `overflow: hidden` would, although I did force-overwrite it. I will try to get the demo to you soon.

**Comment by henriquea** [comment]
@lukasoppermann cool, I'm struggling to visualise it in my head 😅 yes I see how the `overflow: hidden` could be an issue here. I'll see if I can put a jsbin and test it too.

**Comment by lukasoppermann** [comment]
Actually I have a very hard time reproducing the bug in firefox now. I will need to investigate further. However, in this demo you can see that I need to force the `overflow:visible` to allow for the effect.

http://jsbin.com/vibuvemeqa/1/edit?html,css,output

**Comment by henriquea** [comment]
Yeah I know sometimes is hard to replicate the issue out of the context. There's a considerable perf downgrade by using `top|left` and not `transform`I wouldn't recommend. Anyway, I have removed `overflow: hidden` in the latest version. Let me know if I can close this issue.

**Comment by lukasoppermann** [comment]
Thanks, this lets me fix my problem.
