### ISSUE TITLE
Large free-spaces between the cards

### ISSUE THREAD

**Issue by RealCurare** [henriquea/minigrid#61]
Hi,

i get large spaces between my cards like you can see in the image below.

<img width="768" alt="2016-11-24 23_15_22-advena official-nb030005-gi01111" src="https://cloud.githubusercontent.com/assets/12103573/20610633/82502da0-b29c-11e6-81bd-dd2780b0d442.png">

Do you know this issue, is there an easy fix? Maybe with the margin/paddings?
All the div-containers have the same width, no margin and just inner padding of 5px.
The width of the divs is set in percent, but when i dont resize the window there should not be a problem with the with or am i wrong?

Thanks in advance.

curare

**Comment by henriquea** [comment]
Hi @RealCurare, the only thing that comes to my mind now is that if you have async images (aka dynamic images) being loaded minigrid will fail to calculate the element height. In this case you need make sure that images are loaded first before mount the grid.

**Comment by RealCurare** [comment]
Hi @henriquea i tried that, i run the init fuction after the callback of the async event...

**Comment by RealCurare** [comment]
@henriquea I think that was it! The grid now will be initialized in the callback function of the async loading. The most posts are in the right position now. Thanks a lot. -curare

**Comment by henriquea** [comment]
@RealCurare nice! Glad I did help. Closing this issue but feel free to ask again if you need.
