### ISSUE TITLE
Can't create multiple instances of minigrid

### ISSUE THREAD

**Issue by aymanrady** [henriquea/minigrid#8]
having multiple containers on the same page, all items will be used for the first container

```html
<div class="container" id="container-1">
  <div class="item"><img src="http://placehold.it/250x300/4CAF50/fff" alt=""></div>
  <div class="item"><img src="http://placehold.it/250x400/4CAF50/fff" alt=""></div>
  <div class="item"><img src="http://placehold.it/250x200/4CAF50/fff" alt=""></div>
  ...
</div>
<div class="container" id="container-2">
  <div class="item"><img src="http://placehold.it/250x300/F44336/fff" alt=""></div>
  <div class="item"><img src="http://placehold.it/250x400/F44336/fff" alt=""></div>
  <div class="item"><img src="http://placehold.it/250x200/F44336/fff" alt=""></div>
  ....
</div>
```
```js
window.onload = function(){
  minigrid('#container-1', '.item');
};
```

**Comment by aymanrady** [comment]
PR #9

**Comment by bluenaux** [comment]
var containerEle = document.querySelector(containerSelector);
var itemsNodeList = containerEle .querySelectorAll(itemSelector);

**Comment by henriquea** [comment]
Thanks @aymanrady! Got it!

I'm adding some basic tests here and will merge this PR together later today.

Cheers

**Comment by henriquea** [comment]
Hey @bluenaux I appreciate the help but I'd like to keep this project without a wiki for now. I'm already duplicating the content in the README and the gh-pages branch. At some point I'll automate this process. Thanks 😊

**Comment by henriquea** [comment]
Done!
